### ISSUE TITLE
"Add existing" does not unfold the window

### ISSUE THREAD

**Issue by Ladegaard** [zendesklabs/project_app#47]
Hi!

Really appreciate this app - we use it widely in our organization, and usually it only adds value to our work. But today, we seem to be experiencing several issues:

1. When we click "Add existing" button, we have to use the "scrollbar" in order to find the "Ticket ID" field - and the app window appears very small. If we click another time on the "Add existing" button, it resize as it should - see screenshot showing window after one click on "Add existing" button:

![image](https://user-images.githubusercontent.com/35534341/35051206-fb561c26-fba4-11e7-98e7-151017e61502.png)

We started experiencing this issue today - have never had the issue before.

2. Same day, agents started to experience that when either adding an existing ticket, or creating a new using "Create single" button, every third time the ticket would not be saved or related. It seems to be happening intermittently, but does not seem to have a pattern - but I have received 10-15 reports from different agents about the same issue today. I apologize for reporting it so vaguely, but I can't find a pattern or actually reproducing the issue - but it is just happening randomly.

I am wondering if we are the only ones experiencing these issues? 

Thank you so much for all the work with this app - we really find the app highly useful and play an important role in our processes.

Best regards,
Jesper

**Comment by skipjac** [comment]
I haven't heard anything about every 3rd ticket not being related, can you
get some more information on that.

I will work on the add existing expand

Thanks

On Jan 17, 2018 07:50, "Ladegaard" <notifications@github.com> wrote:

Hi!

Really appreciate this app - we use it widely in our organization, and
usually it only adds value to our work. But today, we seem to be
experiencing several issues:

   1. When we click "Add existing" button, we have to use the "scrollbar"
   in order to find the "Ticket ID" field - and the app window appears very
   small. If we click another time on the "Add existing" button, it resize as
   it should - see screenshot showing window after one click on "Add existing"
   button:

[image: image]
<https://user-images.githubusercontent.com/35534341/35051206-fb561c26-fba4-11e7-98e7-151017e61502.png>

We started experiencing this issue today - have never had the issue before.

   1. Same day, agents started to experience that when either adding an
   existing ticket, or creating a new using "Create single" button, every
   third time the ticket would not be saved or related. It seems to be
   happening intermittently, but does not seem to have a pattern - but I have
   received 10-15 reports from different agents about the same issue today. I
   apologize for reporting it so vaguely, but I can't find a pattern or
   actually reproducing the issue - but it is just happening randomly.

I am wondering if we are the only ones experiencing these issues?

Thank you so much for all the work with this app - we really find the app
highly useful and play an important role in our processes.

Best regards,
Jesper

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zendesklabs/project_app/issues/47>, or mute the thread

**Comment by Ladegaard** [comment]
Thank you - appreciate it!

**Comment by Ladegaard** [comment]
Hi,

To further elobarate on the issue we experience, were it seems that the relation between two tickets are not saved correctly - as mentioned this seems to be happening intermittently, but does not seem to have a pattern. 

When we are experiencing the issue, we seem to be seing two things: 1. On the parent ticket, we are not able to see any related tickets 2. On the child ticket, we can only see the child ticket, and no parent ticket. See below screenshots:

Parent ticket:
![parent](https://user-images.githubusercontent.com/35534341/35210183-15121938-ff49-11e7-98ca-3d19c0b67fa3.jpg)

Child ticket:
![child](https://user-images.githubusercontent.com/35534341/35210192-1bfc700e-ff49-11e7-8438-6cbcda6ed359.jpg)

This happens when using the "Create Single" function from the parent ticket. But as I said, it only happens once in a while, and I am not able to identify any patterns to the issue - and therefore, not able to give you steps to reproduce the issue.

It just seems strange to me - as mentioned earlier, this issue first occured January 17th.

**Comment by skipjac** [comment]
I have found the fix for the Add Existing window not expanding. I am working on a couple of other app fixes and should publish later this week.
